### ISSUE TITLE
screenshots are broken

### ISSUE THREAD

**Issue by erenyagdiran** [shurcooL/Conception#11]
Please fix the links.
ty.

**Comment by JuhQ** [comment]
+1

**Comment by bithavoc** [comment]
+1

**Comment by shurcooL** [comment]
Sorry about that, as I've learned, Dropbox public links and HN don't go well toherther:

> This account's public links are generating too much traffic and have been temporarily disabled!

I'll try to do something about it.

**Comment by JuhQ** [comment]
You can host the images here in github and link to them.

**Comment by shurcooL** [comment]
I know, there are many long-term ways to improve this. I'll look into that later.

Should be fixed again now. Feel free to reopen issue if it happens again.

**Comment by erenyagdiran** [comment]
Oh ok. I forgive you already :)
